baseURL = "https://absolutely-nonsensical.github.io/"

languageCode = "zh-CN"
DefaultContentLanguage = "zh-cn"
HasCJKLanguage = true
enableRobotsTXT = true

title = "Absolutely Nonsensical"

theme = "PaperMod"
pagination.pagerSize = 20 

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

    [Params.author]  
        name = "Absolutely Nonsensical"
        bio = ""
        avatar = "img/avatar.png"

[Params.style.vars]
  highlightColor = "#e22d30"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]
