baseURL = "absolutely-nonsensical.github.io"

languageCode = "zh-CN"
DefaultContentLanguage = "zh-cn"
HasCJKLanguage = true
enableRobotsTXT = true

title = "Absolutely Nonsensical"

theme = "mainroad"
paginate = 20
 
[Author]
    name = "Author"
    bio = ""
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

[Params.style.vars]
  highlightColor = "#e22d30"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

